Hardtabs "fix"
DSpeckhals/python-indent pull request #43
Opened 2017-07-06 02:19 UTC by kbrose

* Just return w/o indenting if using hardtabs
* Add minimal help section to readme

2017-07-06 16:26 UTC, DSpeckhals requested changes
Thank you so much for doing this. I think the additions to the README too. There's just a couple of minor nitpicks I have.

2017-07-06 16:26 UTC, DSpeckhals commented on README.md
> +* Check is that you are using "soft tabs" (i.e. spaces). Hard tabs (i.e. `'\t'`) are incompatible with PEP8 compliant indenting so this package gives up if the editor is using hard tabs.
Technically, I think tabs are acceptable, just not for "continued indentation." I would re-word it surrounding that point.

2017-07-06 16:26 UTC, DSpeckhals commented on README.md
> +* Make sure your python code is correctly written -- sometimes what looks like incorrect indentation is actually being caused by a bracket twenty lines ago that somehow lost its closing partner!
Capitalize "python"

2017-07-06 17:40 UTC, kbrose commented on README.md
> +* Check is that you are using "soft tabs" (i.e. spaces). Hard tabs (i.e. `'\t'`) are incompatible with PEP8 compliant indenting so this package gives up if the editor is using hard tabs.
note to self: also fix grammar "Check is that..."

2017-07-07 03:04 UTC, kbrose commented
@DSpeckhals thanks for the review. Latest commit should address comments.

2017-07-07 03:18 UTC, kbrose commented
This will close #42

2017-07-07 13:25 UTC, DSpeckhals approved these changes

2017-07-07 13:26 UTC, merged