WIP: Reindent feature
DSpeckhals/python-indent pull request #44
Opened 2017-07-06 05:18 UTC by kbrose

# Summary
Attempting to add a "reindent" feature.

I often find myself changing the name of something which ends up changing the PEP8 indentation. E.g.

```python
def fun_name(arg1,
             arg2):
```

might get changed to

```python
def my_fun_name(arg1,
             arg2):
```

and then I have to manually re-hit enter on these lines. It would be nice to have a command to re-indent automagically.

## TODO

This is a work in progress b/c it's broken in some cases. It has problems with places that should dedent, e.g. it breaks on

```python
def test(param_a, param_b, param_c,
         param_d):
    pass

def test(param_a,
         param_b,
         param_c):
    pass

class TheClass(object):
    def test(param_a, param_b,
             param_c):
        a_list = ["1", "2", "3",
                  "4"]
```
by changing it to
```python
def test(param_a, param_b, param_c,
         param_d):
    pass

    def test(param_a,
             param_b,
             param_c):
        pass

        class TheClass(object):
            def test(param_a, param_b,
                     param_c):
                a_list = ["1", "2", "3",
                          "4"]

```

2017-07-06 16:20 UTC, DSpeckhals commented
I like it so far. Thanks for doing this; I think it's a reasonable feature.

2017-07-07 15:15 UTC, kbrose commented
This PR in python-language should fix the issue raised above. https://github.com/atom/language-python/pull/204

2017-07-14 15:15 UTC, kbrose commented
Once https://github.com/atom/atom/pull/15008 makes it in (and next version of Atom is released) the bug described above should be fixed. At that point I'll pick up development again

2017-07-19 15:40 UTC, DSpeckhals requested changes
Can you write some tests for reindenting also?

Thanks for the PR!

2017-07-19 15:40 UTC, DSpeckhals commented on lib/python-indent.js
> +        if (!this.editor ||
Can you move this and the same code for halting in `PythonIndent.indent` out into a separate function?

2017-07-19 15:40 UTC, DSpeckhals commented on lib/python-indent.js
> +            const editorElement = atom.views.getView(atom.workspace.getActiveTextEditor());
I think you can use `this.editor` here instead of `atom.workspace.getActiveTextEditor`.

2017-08-14 15:02 UTC, kbrose commented
Update: I thought the updated `language-python` (0.45.4) would be released with v1.19 of Atom, but it looks like it'll be in v1.20 instead. I'm also wondering if this feature makes more sense as a standalone package since it's pretty independent of the python language/indenting -- I'm really just re-sending the newline signal for each newline to trigger indentation...

2017-09-02 17:26 UTC, kbrose commented
Closing in favor of https://atom.io/packages/reindent

2017-09-02 17:26 UTC, closed without merging